Add adjustable memory values for operator deployments
Dynatrace/helm-charts pull request #168
Opened 2021-12-15 11:03 UTC by ralfzen

2021-12-16 14:34 UTC, ralfzen commented
I've adapted the sections and added the values for cpu.

2021-12-16 16:12 UTC, chrismuellner requested changes

2021-12-17 09:21 UTC, ralfzen commented
Values are swapped into the k8s order.

2021-12-17 10:05 UTC, chrismuellner approved these changes

2021-12-21 12:10 UTC, merged